making white space consistent in script

diff --git a/start-spark-cluster b/start-spark-cluster
--- a/start-spark-cluster
+++ b/start-spark-cluster
@@ -176,17 +176,17 @@ echo "Starting Zoo. Log file is ${ZOO_LOG}"
 COUNT=65
 ZOO_UP=""
 until [ $COUNT -lt 0 ]; do
-	sleep 1
-	ZOO_UP=$(echo 'ruok' | nc localhost 2181)
-	if [ -z "$ZOO_UP" ]; then
-					break
-	fi
-	let COUNT-=1
+    sleep 1
+    ZOO_UP=$(echo 'ruok' | nc localhost 2181)
+    if [ -z "$ZOO_UP" ]; then
+                    break
+    fi
+    let COUNT-=1
 done
 
 if [ $COUNT -eq 0 ]; then
-	echo "ZooKeeper did not start up properly, aborting startup. Please check ${RUN_DIR}/zoo.log for more information"
-	exit 5
+    echo "ZooKeeper did not start up properly, aborting startup. Please check ${RUN_DIR}/zoo.log for more information"
+    exit 5
 fi
   
 YARN_LOG="${RUN_DIR}/yarn.log"
