DB-4960 StressSparkIT

diff --git a/hbase_sql/src/test/bin/start-splice-its b/hbase_sql/src/test/bin/start-splice-its
--- a/hbase_sql/src/test/bin/start-splice-its
+++ b/hbase_sql/src/test/bin/start-splice-its
@@ -63,8 +63,29 @@ fi
 echo "Starting ZooKeeperServerMain, log file is ${ZOOLOG}"
 mvn -B exec:exec -P${PROFILE},spliceZoo > ${ZOOLOG} 2>&1 &
 
-echo "waiting 60 seconds for Zookeeper startup (needs time to clean up prior sessions)..."
-sleep 65
+#######################################################################################################
+# Wait for up to 65 seconds for zoo to start, checking nc periodically to see if we are connected
+# This makes use of ZooKeeper's 'Four-Letter Words' commands to determine the liveness of ZooKeeper
+# In particular, it uses netcat (nc) to pipe the command 'ruok' to zookeeper on it's connection port.
+# If ZooKeeper responds with 'imok', then the server is up. If it returns empty, then zookeeper
+# hasn't started yet. If the count goes to 0, and we never got 'imok', then we want to blow up because
+# ZooKeeper didn't start up properly
+#######################################################################################################
+COUNT=65
+ZOO_UP=""
+until [ $COUNT -lt 0 ]; do
+    sleep 1
+    ZOO_UP=$(echo 'ruok' | nc localhost 2181)
+    if [ -z "$ZOO_UP" ]; then
+                    break
+    fi
+    let COUNT-=1
+done
+
+if [ $COUNT -eq 0 ]; then
+    echo "ZooKeeper did not start up properly, aborting startup. Please check ${RUN_DIR}/zoo.log for more information"
+    exit 5
+fi
 
 # Start SpliceTestYarnPlatform in background.
 echo "Starting SpliceTestYarnPlatform, log file is ${YARNLOG}"
